### PR TITLE
fix: replace all occurrences of a matching class mapping

### LINKED ISSUE #1: Replace logic replaces only the first occurrence but not all
The current `replace` just replaces the first occurrence but not all. (see https://github.com/dpa99c/cordova-plugin-androidx-adapter/blob/master/apply.js#L49)
 
E.g. with this plugin https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/notification/Options.java#L46-L52 only one line is replaced resulting in a build failure.

A PR is incoming, **edit**: #2  
And a BIG thanks for these two plugins, really awesome work!

### PR DESCRIPTION
**Pull request by timbru31**
this fixes and closes #1

### CODE REVIEW

**Comment by dpa99c** [comment]
lol, thanks. can't believe I forgot to make it a global regex 😊

**Comment by dpa99c** [comment]
will push this out to npm in a patch version shortly

**Comment by timbru31** [comment]
Thanks for the quick review & merge :)

**Comment by dpa99c** [comment]
published to npm as v1.0.1

**Comment by timbru31** [comment]
Thanks!

**Pull request merged**
